services:
  - type: web
    plan: free
    name: swiftgo
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn swiftgo.asgi:application -k uvicorn.workers.UvicornWorker' 