# Generated by Django 5.0.8 on 2025-06-01 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("office_lat", models.FloatField()),
                ("office_long", models.FloatField()),
                ("geofence_radius", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("clock_in_time", models.DateTimeField(blank=True, null=True)),
                ("clock_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "clock_in_location_latitude",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "clock_in_location_longitude",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "clock_out_location_latitude",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "clock_out_location_longitude",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
