# Generated by Django 5.0.8 on 2025-06-16 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("office_lat", models.FloatField()),
                ("office_long", models.FloatField()),
                ("geofence_radius", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("attachee", "Attachee"),
                            ("supervisor", "Supervisor"),
                        ],
                        default="attachee",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("checkin_time", models.DateTimeField(blank=True, null=True)),
                ("checkout_time", models.DateTimeField(blank=True, null=True)),
                ("checkin_latitude", models.FloatField(blank=True, null=True)),
                ("checkin_longitude", models.FloatField(blank=True, null=True)),
                ("checkout_latitude", models.FloatField(blank=True, null=True)),
                ("checkout_longitude", models.FloatField(blank=True, null=True)),
                ("checkin_address", models.TextField(blank=True, null=True)),
                ("checkout_address", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
