# Generated by Django 5.0.8 on 2025-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="clock_in_location_latitude",
            new_name="checkin_latitude",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="clock_in_location_longitude",
            new_name="checkin_longitude",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="clock_in_time",
            new_name="checkin_time",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="clock_out_location_latitude",
            new_name="checkout_latitude",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="clock_out_location_longitude",
            new_name="checkout_longitude",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="clock_out_time",
            new_name="checkout_time",
        ),
        migrations.AddField(
            model_name="attendance",
            name="checkin_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="checkout_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
