# Generated by Django 5.0.8 on 2025-06-28 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geofence",
            name="office_name",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("staff", "Staff"), ("member", "Member")],
                default="member",
                help_text="Determines if the user is staff (admin) or a member.",
                max_length=10,
            ),
        ),
    ]
