# Generated by Django 5.2.4 on 2025-07-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_customuser_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("communication", "Communication"),
                    ("creatives", "Creatives"),
                    ("tech_department", "Tech Department"),
                    ("community_experience", "Community Experience"),
                    ("youth_engagement", "Youth Engagement"),
                    ("heritage", "Heritage"),
                    ("admin", "Admin"),
                    ("finance", "Finance"),
                    ("entrepreneurship", "Entrepreneurship"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
